/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_vacunacion;

import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Luis
 */
public class Preguntas extends javax.swing.JFrame {

    private String[] getPregunta;

    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }
    
//    int posicion = 0;
//    Respuestas r = new Respuestas();
//    Preguntas p = new Preguntas();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Enviar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn4 = new rojerusan.RSButtonIconI();
        btn1 = new rojerusan.RSButtonIconI();
        btn2 = new rojerusan.RSButtonIconI();
        btn3 = new rojerusan.RSButtonIconI();
        rSPanelsSlider2 = new rojerusan.RSPanelsSlider();
        pnl3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        opc1 = new javax.swing.JRadioButton();
        opc2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        opc3 = new javax.swing.JRadioButton();
        opc4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        opc5 = new javax.swing.JRadioButton();
        opc6 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        opc7 = new javax.swing.JRadioButton();
        opc8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        opc9 = new javax.swing.JRadioButton();
        opc10 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        opc11 = new javax.swing.JRadioButton();
        opc12 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        opc13 = new javax.swing.JRadioButton();
        opc14 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        opc15 = new javax.swing.JRadioButton();
        opc16 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        opc17 = new javax.swing.JRadioButton();
        opc18 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        opc19 = new javax.swing.JRadioButton();
        opc20 = new javax.swing.JRadioButton();
        btnTerminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AUTOTEST COVID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 1, 24))); // NOI18N

        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        Regresar.setText("<<Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/rr.png"))); // NOI18N
        btn4.setText("Resultados");
        btn4.setToolTipText("");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 220, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bienvenida.png"))); // NOI18N
        btn1.setText("Bienvenida");
        btn1.setToolTipText("");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/busq.png"))); // NOI18N
        btn2.setText("A cerca de");
        btn2.setToolTipText("");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 220, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tett.png"))); // NOI18N
        btn3.setText("Auto-Test Covid");
        btn3.setToolTipText("");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, -1));

        rSPanelsSlider2.setBackground(new java.awt.Color(255, 255, 255));

        pnl3.setBackground(new java.awt.Color(255, 255, 255));
        pnl3.setName("pnl3"); // NOI18N

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18)); // NOI18N
        jLabel1.setText("Responde el test para saber tu estado de salud ");
        jLabel1.setToolTipText("");

        question1.setText("1.-¿Tuvo usted algún contacto a menos de 2 metros durante un mínimo de 15 minutos o convive/cuida a alguna persona con COVID-19?    ");

        buttonGroup1.add(opc1);
        opc1.setText("SI");
        opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opc2);
        opc2.setText("NO");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });

        jLabel3.setText("2.-¿Presenta usted algún síntoma?");

        buttonGroup2.add(opc3);
        opc3.setText("SI");

        buttonGroup2.add(opc4);
        opc4.setText("NO");
        opc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc4ActionPerformed(evt);
            }
        });

        jLabel4.setText("3.-¿Hace más de 14 días que comenzaron los síntomas?");

        buttonGroup3.add(opc5);
        opc5.setText("SI");

        buttonGroup3.add(opc6);
        opc6.setText("NO");
        opc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc6ActionPerformed(evt);
            }
        });

        jLabel5.setText("4.-¿Tiene dificultad repentina para respirar o nota falta de aire?  ");

        buttonGroup4.add(opc7);
        opc7.setText("SI");

        buttonGroup4.add(opc8);
        opc8.setText("NO");
        opc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc8ActionPerformed(evt);
            }
        });

        jLabel6.setText("5.-¿Presenta fiebre de más de 37,7ºC?");

        buttonGroup5.add(opc9);
        opc9.setText("SI");

        buttonGroup5.add(opc10);
        opc10.setText("NO");
        opc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc10ActionPerformed(evt);
            }
        });

        jLabel7.setText("6.-¿Su temperatura es mayor de 39ºC?");

        buttonGroup6.add(opc11);
        opc11.setText("SI");

        buttonGroup6.add(opc12);
        opc12.setText("NO");
        opc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc12ActionPerformed(evt);
            }
        });

        jLabel8.setText("7.-¿Tiene recientemente tos persistente?  ");

        buttonGroup7.add(opc13);
        opc13.setText("SI");

        buttonGroup7.add(opc14);
        opc14.setText("NO");
        opc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc14ActionPerformed(evt);
            }
        });

        jLabel9.setText("8.-¿Percibe pérdida o alteración repentina del gusto u olfato?");

        buttonGroup8.add(opc15);
        opc15.setText("SI");

        buttonGroup8.add(opc16);
        opc16.setText("NO");
        opc16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc16ActionPerformed(evt);
            }
        });

        jLabel10.setText("9.-¿Nota malestar general, cansancio excesivo o dolor muscular/articular importante sin justificación aparente?");

        buttonGroup9.add(opc17);
        opc17.setText("SI");

        buttonGroup9.add(opc18);
        opc18.setText("NO");
        opc18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc18ActionPerformed(evt);
            }
        });

        jLabel11.setText("10.-¿Presenta dolor de garganta, cabeza o abdominal considerable?");

        buttonGroup10.add(opc19);
        opc19.setText("SI");

        buttonGroup10.add(opc20);
        opc20.setText("NO");
        opc20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc20ActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc13)
                        .addGap(18, 18, 18)
                        .addComponent(opc14))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc11)
                        .addGap(18, 18, 18)
                        .addComponent(opc12))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc9)
                        .addGap(18, 18, 18)
                        .addComponent(opc10))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc7)
                        .addGap(18, 18, 18)
                        .addComponent(opc8))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc5)
                        .addGap(18, 18, 18)
                        .addComponent(opc6))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc3)
                        .addGap(18, 18, 18)
                        .addComponent(opc4))
                    .addComponent(question1)
                    .addComponent(jLabel3)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(opc1)
                        .addGap(18, 18, 18)
                        .addComponent(opc2))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(opc17)
                                .addGap(18, 18, 18)
                                .addComponent(opc18))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(opc15)
                                .addGap(18, 18, 18)
                                .addComponent(opc16))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(opc19)
                                .addGap(18, 18, 18)
                                .addComponent(opc20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTerminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question1)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc1)
                            .addComponent(opc2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc3)
                            .addComponent(opc4))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc5)
                            .addComponent(opc6))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc7)
                            .addComponent(opc8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc9)
                            .addComponent(opc10))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc11)
                            .addComponent(opc12))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc13)
                            .addComponent(opc14))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc15)
                            .addComponent(opc16))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc17)
                            .addComponent(opc18))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc19)
                            .addComponent(opc20))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTerminar)
                            .addComponent(btnLimpiar)))))
        );

        rSPanelsSlider2.add(pnl3, "card2");

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setName("pnl1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("La Pandemia del Covid-19 ha recrudecido en nuestra provincia y es \nimportante continuar con los cuidados a fin de disminuir el número\nde contagios.\nDe acuerdo a los reportes de los Centros de Salud, los mismos \nestán sobrepasados de ocupación y es imperioso descomprimir la \ncantidad de pacientes.\n \nLa pandemia no terminó, el virus continúa entre nosotros. \nPara reducir las posibilidades de contagios, cuidate y cuidá a \ntus seres queridos. Seamos responsables.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel2.setText("Centro Universitario UAEM Valle de Chalco");

        jLabel12.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel12.setText("ingenieria en computacion");

        jLabel13.setFont(new java.awt.Font("BankGothic Lt BT", 3, 18)); // NOI18N
        jLabel13.setText("Test de Covid 19");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        rSPanelsSlider2.add(pnl1, "card3");

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setName("pnl4"); // NOI18N

        jLabel14.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel14.setText("Resultados");

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel14)
                .addContainerGap(607, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel14)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        rSPanelsSlider2.add(pnl4, "card4");

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setName("pnl2"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("La Pandemia del Covid-19 ha recrudecido en nuestra provincia y es importante continuar \ncon los cuidados a fin de disminuir el número de contagios.\nDe acuerdo a los reportes de los Centros de Salud, los mismos están sobrepasados de \nocupación y es imperioso descomprimir la cantidad de pacientes.\n \nLa pandemia no terminó, el virus continúa entre nosotros. Para reducir las posibilidades \nde contagios, cuidate y cuidá a tus seres queridos. Seamos responsables.\n \n Entre todos podemos colaborar con estas simples acciones\n \n    Lavarnos las manos con agua y jabón frecuentemente\n    Evitar tocarnos los ojos, la boca y la nariz.\n    Ventilar los ambientes\n    Usar barbijos\n    Toser y estornudar en el pliegue interno del codo\n    En la medida de lo posible, quedarnos en casa la mayor parte del tiempo\n    Mantener distancia prudencial con las demás personas\n    Usar nuestros propios elementos en los lugares de trabajo y no compartir el mate.");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel15.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel15.setText("Que Puedes hacer para prevenir la propagacion del virus");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        rSPanelsSlider2.add(pnl2, "card5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelsSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1640, 1640, 1640)
                .addComponent(Regresar)
                .addGap(18, 18, 18)
                .addComponent(Enviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar)
                    .addComponent(Regresar)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelsSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Autotest Covid");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc10ActionPerformed

    private void opc16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc16ActionPerformed

    private void opc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc14ActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc2ActionPerformed

    private void opc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc12ActionPerformed

    private void opc18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc18ActionPerformed

    private void opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc1ActionPerformed

    private void opc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc6ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        //         int count=0;
        //        if(opc1.isSelected()){
            //            count=count+1;
            //        }else{
            //            if(opc2.isSelected()){
                //                count=count+1;
                //            }
            //            if(opc3.isSelected()){
                //            count=count+1;
                //        }else{
                //            if(opc4.isSelected()){
                    //                count=count+1;
                    //                JOptionPane.showMessageDialog(null, "count:"+count);
                    //            }}
            //        }
    }//GEN-LAST:event_EnviarActionPerformed

    private void opc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc8ActionPerformed

    private void opc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc4ActionPerformed

    private void opc20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc20ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (!this.btn3.isSelected()){
            this.btn2.setSelected(false);
            this.btn1.setSelected(false);
            this.btn4.setSelected(false);
            this.btn3.setSelected(true);
            rSPanelsSlider2.setPanelSlider(20,pnl3,RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (!this.btn1.isSelected()){
            this.btn2.setSelected(false);
            this.btn3.setSelected(false);
            this.btn4.setSelected(false);
            this.btn1.setSelected(true);
            rSPanelsSlider2.setPanelSlider(20,pnl1,RSPanelsSlider.DIRECT.RIGHT);
 }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        if (!this.btn2.isSelected()){
            this.btn1.setSelected(false);
            this.btn3.setSelected(false);
            this.btn4.setSelected(false);
            this.btn2.setSelected(true);
            rSPanelsSlider2.setPanelSlider(20,pnl2,RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (!this.btn4.isSelected()){
            this.btn2.setSelected(false);
            this.btn3.setSelected(false);
            this.btn1.setSelected(false);
            this.btn4.setSelected(true);
            rSPanelsSlider2.setPanelSlider(20,pnl4,RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Regresar;
    private rojerusan.RSButtonIconI btn1;
    private rojerusan.RSButtonIconI btn2;
    private rojerusan.RSButtonIconI btn3;
    private rojerusan.RSButtonIconI btn4;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton opc1;
    private javax.swing.JRadioButton opc10;
    private javax.swing.JRadioButton opc11;
    private javax.swing.JRadioButton opc12;
    private javax.swing.JRadioButton opc13;
    private javax.swing.JRadioButton opc14;
    private javax.swing.JRadioButton opc15;
    private javax.swing.JRadioButton opc16;
    private javax.swing.JRadioButton opc17;
    private javax.swing.JRadioButton opc18;
    private javax.swing.JRadioButton opc19;
    private javax.swing.JRadioButton opc2;
    private javax.swing.JRadioButton opc20;
    private javax.swing.JRadioButton opc3;
    private javax.swing.JRadioButton opc4;
    private javax.swing.JRadioButton opc5;
    private javax.swing.JRadioButton opc6;
    private javax.swing.JRadioButton opc7;
    private javax.swing.JRadioButton opc8;
    private javax.swing.JRadioButton opc9;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JLabel question1;
    private rojerusan.RSPanelsSlider rSPanelsSlider2;
    // End of variables declaration//GEN-END:variables
}
