package Model;
// Generated 23/09/2021 01:45:14 PM by Hibernate Tools 4.3.1



/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca  implements java.io.Serializable {


     private Integer idBliblioteca;
     private String direccion;
     private String nombre;
     private Long telefono;
     private String correo;
     private String claveTrabajo;

    public Biblioteca() {
    }

    public Biblioteca(String direccion, String nombre, Long telefono, String correo, String claveTrabajo) {
       this.direccion = direccion;
       this.nombre = nombre;
       this.telefono = telefono;
       this.correo = correo;
       this.claveTrabajo = claveTrabajo;
    }
   
    public Integer getIdBliblioteca() {
        return this.idBliblioteca;
    }
    
    public void setIdBliblioteca(Integer idBliblioteca) {
        this.idBliblioteca = idBliblioteca;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getClaveTrabajo() {
        return this.claveTrabajo;
    }
    
    public void setClaveTrabajo(String claveTrabajo) {
        this.claveTrabajo = claveTrabajo;
    }




}


