package Model;
// Generated 23/09/2021 01:45:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer idConsulta;
     private Empleado empleado;
     private Libro libro;
     private Visitante visitante;
     private String titulo;
     private Date fecha;
     private Date hora;
     private Date devolucion;
     private String seccion;
     private String generoLibro;
     private String prestamo;
     private String estadoDevolucion;

    public Consulta() {
    }

    public Consulta(Empleado empleado, Libro libro, Visitante visitante, String titulo, Date fecha, Date hora, Date devolucion, String seccion, String generoLibro, String prestamo, String estadoDevolucion) {
       this.empleado = empleado;
       this.libro = libro;
       this.visitante = visitante;
       this.titulo = titulo;
       this.fecha = fecha;
       this.hora = hora;
       this.devolucion = devolucion;
       this.seccion = seccion;
       this.generoLibro = generoLibro;
       this.prestamo = prestamo;
       this.estadoDevolucion = estadoDevolucion;
    }
   
    public Integer getIdConsulta() {
        return this.idConsulta;
    }
    
    public void setIdConsulta(Integer idConsulta) {
        this.idConsulta = idConsulta;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Visitante getVisitante() {
        return this.visitante;
    }
    
    public void setVisitante(Visitante visitante) {
        this.visitante = visitante;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Date getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Date devolucion) {
        this.devolucion = devolucion;
    }
    public String getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }
    public String getGeneroLibro() {
        return this.generoLibro;
    }
    
    public void setGeneroLibro(String generoLibro) {
        this.generoLibro = generoLibro;
    }
    public String getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(String prestamo) {
        this.prestamo = prestamo;
    }
    public String getEstadoDevolucion() {
        return this.estadoDevolucion;
    }
    
    public void setEstadoDevolucion(String estadoDevolucion) {
        this.estadoDevolucion = estadoDevolucion;
    }




}


